### ISSUE TITLE
options.exclude.includes is not a function

### ISSUE THREAD

**Issue by steveblue** [cebor/rollup-plugin-angular#5]
v0.2.4 seems to break bundling a very simple angular web application, only has app.module defined and one other @Injectable. Rolling back to v0.2.2 bundles the same application.

rollup -c rollup.config.js

TypeError: options.exclude.includes is not a function
    at angular (/Users/steve/www/synth-iframe/node_modules/rollup-plugin-angular/dist/rollup-plugin-angular.js:31:24)
    at Object.<anonymous> (/Users/steve/www/synth-iframe/rollup.config.js:18:5)
    at Module._compile (module.js:413:34)
    at Object.require.extensions..js (/Users/steve/.nvm/versions/node/v5.5.0/lib/node_modules/rollup/bin/rollup:729:8)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/steve/.nvm/versions/node/v5.5.0/lib/node_modules/rollup/bin/rollup:736:19
    at process._tickCallback (node.js:401:9)

**Comment by cebor** [comment]
@steveblue can you show your rollup.config.js, please ...

And which nodeversion are you running.

Seems that your node, does not support `Array.prototype.includes()`

**Comment by cebor** [comment]
fixed in e9d7496cec6bf2623d5061eb7688b8f3a3b7e73a
